/*
 * This file is subject to the terms and conditions of the GNU Lesser
 * General Public License v2.1. See the file LICENSE in the top level
 * directory for more details.
 */

/******************************************************************************
* Copyright (C) 1994-2017 Lua.org, PUC-Rio.
*
* Permission is hereby granted, free of charge, to any person obtaining
* a copy of this software and associated documentation files (the
* "Software"), to deal in the Software without restriction, including
* without limitation the rights to use, copy, modify, merge, publish,
* distribute, sublicense, and/or sell copies of the Software, and to
* permit persons to whom the Software is furnished to do so, subject to
* the following conditions:
*
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
******************************************************************************/

/**
 * @ingroup     pkg
 * @{
 *
 * @file        lua_run_char_array.c
 * @brief       Implementation of lua_run_char_array,  which runs a char array
 *              as a lua script.
 *
 * @author      Daniel Petry <daniel.petry@fu-berlin.de>
 *
 * @}
 */

#include <stdlib.h>
#include "lauxlib.h"
#include "lualib.h"

static lua_State *globalL = NULL;

//static const char *progname = "lua";



/*
** Prints an error message, adding the program name in front of it
** (if present)
*/
//static void l_message (const char *pname, const char *msg) {
//  if (pname) lua_writestringerror("%s: ", pname);
//  lua_writestringerror("%s\n", msg);
//}
//
//
///*
//** Check whether 'status' is not OK and, if so, prints the error
//** message on the top of the stack. It assumes that the error object
//** is a string, as it was either generated by Lua or by 'msghandler'.
//*/
//static int report (lua_State *L, int status) {
//  if (status != LUA_OK) {
//    const char *msg = lua_tostring(L, -1);
//    l_message(progname, msg);
//    lua_pop(L, 1);  /* remove message */
//  }
//  return status;
//}


/*
** Message handler used to run all chunks
*/
static int msghandler (lua_State *L) {
  const char *msg = lua_tostring(L, 1);
  if (msg == NULL) {  /* is error object not a string? */
    if (luaL_callmeta(L, 1, "__tostring") &&  /* does it have a metamethod */
        lua_type(L, -1) == LUA_TSTRING)  /* that produces a string? */
      return 1;  /* that is the message */
    else
      msg = lua_pushfstring(L, "(error object is a %s value)",
                               luaL_typename(L, 1));
  }
  luaL_traceback(L, L, msg, 1);  /* append a standard traceback */
  return 1;  /* return the traceback */
}


/*
** Interface to 'lua_pcall', which sets appropriate message function
** and C-signal handler. Used to run all chunks.
*/
static int docall (lua_State *L) {
  int status;
  int base = lua_gettop(L);  /* function index */
  lua_pushcfunction(L, msghandler);  /* push message handler */
  lua_insert(L, base);  /* put it under function and args */
  globalL = L;  /* to be available to 'laction' */
  status = lua_pcall(L, 0, 0, base);
  lua_remove(L, base);  /* remove message handler from the stack */
  return status;
}


//static int dochunk (lua_State *L, int status) {
//  if (status == LUA_OK) status = docall(L, 0, 0);
// return report(L, status);
//}


int lua_run_char_array (char *buffer, size_t buffer_len ){
  int status;
  lua_State *L = luaL_newstate();  /* create state */
  luaL_checkversion(L);
  luaL_openlibs(L);

  if (L == NULL) {
    puts("cannot create state: not enough memory");
    return EXIT_FAILURE;
  }
  
  
  
   luaL_loadbuffer(L, buffer, buffer_len, "lua input script");
  
  status = docall(L);
  
  if (status != LUA_OK){
	  puts("Lua script running failed");
  }
  
  lua_close(L);

  return (status == LUA_OK) ? EXIT_SUCCESS : EXIT_FAILURE;
}
